package com.trodar.theme.colors

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFC8BFFF)
val md_theme_dark_onPrimary = Color(0xFF2E0E93)
val md_theme_dark_primaryContainer = Color(0xFF413F47)
val md_theme_dark_onPrimaryContainer = Color(0xFFE5DEFF)
val md_theme_dark_secondary = Color(0xFFA2A2A2)
val md_theme_dark_onSecondary = Color(0xFF312E41)
val md_theme_dark_secondaryContainer = Color(0xFF3D3D3D)
val md_theme_dark_onSecondaryContainer = Color(0xFFE5DFF9)
val md_theme_dark_tertiary = Color(0xFFA27322)
val md_theme_dark_onTertiary = Color(0xFF482536)
val md_theme_dark_tertiaryContainer = Color(0xFF613B4D)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF48454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C5D0)
val md_theme_dark_outline = Color(0xFF928F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inversePrimary = Color(0xFF5D4BC2)
val md_theme_dark_surfaceTint = Color(0xFFC8BFFF)
val md_theme_dark_outlineVariant = Color(0xFF48454F)
val md_theme_dark_scrim = Color(0xFF000000)