package com.trodar.theme.colors

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2C40B9)
val md_theme_light_onPrimary = Color(0xFFFFFBFF)
val md_theme_light_primaryContainer = Color(0xFFFFFFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF3B4563)
val md_theme_light_secondary = Color(0xFF5F5C71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE7E7E7)
val md_theme_light_onSecondaryContainer = Color(0xFF1C192B)
val md_theme_light_tertiary = Color(0xFFA25922)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8E7)
val md_theme_light_onTertiaryContainer = Color(0xFF301121)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF3F3F3)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE5E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF48454F)
val md_theme_light_outline = Color(0xFF78767F)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFC8BFFF)
val md_theme_light_surfaceTint = Color(0xFF5D4BC2)
val md_theme_light_outlineVariant = Color(0xFFC9C5D0)
val md_theme_light_scrim = Color(0xFF000000)
val testcolor = Color(0xFF249433)